[package]
name = "polygon_shader"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
imageproc = "0.23.0"
rand = "0.8.3"